USE SubZeroPOS;
GO

ALTER TABLE RestaurantSettings
ADD DateFormat VARCHAR(30) NOT NULL DEFAULT 'yyyy-MM-dd HH:mm',
    ShowCashierNameOnInvoice BIT NOT NULL DEFAULT 1;
GO

SELECT COLUMN_NAME, DATA_TYPE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'RestaurantSettings'
ORDER BY ORDINAL_POSITION;
GO
