USE SubZeroPOS;
GO

ALTER TABLE Orders
ADD PaymentMethodCode NVARCHAR(20) NOT NULL DEFAULT 'Cash';
GO

-- Optional: verify the change
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Orders'
ORDER BY ORDINAL_POSITION;
GO
